### ISSUE TITLE
linux系统下data/pcrjjc文件夹创建位置不正确

### ISSUE THREAD

**Issue by PackageInstaller** [reine-ishyanami/nonebot-plugin-pcrjjc#1]
如题，这个文件夹本应该创建在data/pcrjjc,但是却在bot根目录创建了一个名为“data\pcrjjc”的文件夹

**Comment by reine-ishyanami** [comment]
> 如题，这个文件夹本应该创建在data/pcrjjc,但是却在bot根目录创建了一个名为“data\pcrjjc”的文件夹

`0.1.4`版本修复

**Comment by PackageInstaller** [comment]
已解决
