### ISSUE TITLE
验证码

### ISSUE THREAD

**Issue by matlabnmb1** [reine-ishyanami/nonebot-plugin-pcrjjc#2]
![QQ截图20240105105410](https://github.com/reine-ishyanami/nonebot-plugin-pcrjjc/assets/154576462/ba65b44e-6e5c-4895-8b50-ff324af49f50)
pcr账号登录需要验证码，请完成以下链接中的验证内容后将第1个方框的内容点击复制

但是没发送链接，根本验证不了

**Comment by reine-ishyanami** [comment]
最新版本已修复，更新下即可

**Comment by matlabnmb1** [comment]
十分感谢，已经连上了
